.app-common-build-pipeline: &app-common-build-pipeline # 使用YAML锚点功能，方便配置复用
  docker:
    image: node:22
  ifModify:
    - apps/${CNB_PIPELINE_KEY}/** # 当前应用更新
    - packages/**/** #依赖包更新
  stages:
    - name: 编译构建
      script: npm install && npm run build:${CNB_PIPELINE_KEY}
    - name: 查看编译结果
      script: npm install && npm run build

master:
  push:
    web-console-passport: *app-common-build-pipeline
    web-console-home: *app-common-build-pipeline
